import React, { ReactNode } from 'react';
import Head from 'next/head';
import Script from 'next/script'
import Link from 'next/link';
import Header from '../Header';
import Footer from '../Footer';
import Sidebar from '../Sidebar';

type Props = {
    children: ReactNode;
    title?: string;
};

const MainLayout = ({
    children,
    title = 'Home Page Example',
}: Props) => (
    <>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="../assets/node_modules/morrisjs/morris.css" rel="stylesheet" />
            <link href="assets/css/style.min.css" rel="stylesheet" />
            <link href="assets/css/pages/dashboard4.css" rel="stylesheet" />
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />

        </Head>
        <Header />
        <Sidebar />
        <main>
            {children}
        </main>
        <Footer />


        <Script src="assets/node_modules/jquery/dist/jquery.min.js" />
        <Script src="assets/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js" />
        <Script src="assets/js/perfect-scrollbar.jquery.min.js" />
        <Script src="assets/js/waves.js" />
        <Script src="assets/js/sidebarmenu.js" />
        <Script src="assets/js/custom.min.js" />
        <Script src="assets/node_modules/skycons/skycons.js" />
        <Script src="assets/node_modules/raphael/raphael-min.js" />
        <Script src="assets/node_modules/morrisjs/morris.min.js" />
        <Script src="assets/node_modules/jquery-sparkline/jquery.sparkline.min.js" />
        {/* <Script src="assets/js/dashboard4.js" /> */}


    </>
);

export default MainLayout;